import "./globals.css";
import { Inter } from "next/font/google";
import ContextWrapper from "@/context/global-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "To Do Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ContextWrapper>{children}</ContextWrapper>
			</body>
		</html>
	);
}
